### ISSUE TITLE
Unnecessary normal mode <c-e> map

### ISSUE THREAD

**Issue by Anfid** [chambln/kakoune-readline#1]
Generally plugins should avoid adding any normal mode maps, especially to simple things, like entering insert mode. In cases, where it is necessary, there should be an option to opt-out.

The only normal mode map from this plugin ended up messing up my go-to-definition map.

**Comment by chambln** [comment]
I'm not quite sure why I added that mapping. Maybe just for
completeness. From **readline**(1):

> **emacs-editing-mode (C-e)**
> 
> When in **vi** command mode, this causes a switch to **emacs**
> editing mode.

But I can't imagine anyone using `<c-e>` instead of `i` in Kakoune. So yeah, not worth including a normal mapping for.

Thanks for pointing that out.
